### ISSUE TITLE
Curl output will fill buffer unless pipes or re-directed.

### ISSUE THREAD

**Issue by cloudpitchford** [IBM-Bluemix-Docs/key-protect#3]
I had to resubmit my request appending `> token.json` to the end, or the output would just fill the buffer of the terminal window.

**Comment by ccbarragan** [comment]
Hi! We've updated our doc examples to include your feedback:

- https://cloud.ibm.com/docs/services/key-protect?topic=key-protect-retrieve-access-token#retrieve-token-api
- https://cloud.ibm.com/apidocs/key-protect

If you find anything else, let us know. Thanks for helping to improve our docs!
