### ISSUE TITLE
Incorrect CLI references

### ISSUE THREAD

**Issue by wmwidener** [IBM-Bluemix-Docs/key-protect#8]
The [Key Protect CLI Reference](https://cloud.ibm.com/docs/services/key-protect?topic=key-protect-cli-reference) material shows these confusing command lines:
`ibmcloud kp create KEY_NAME -i INSTANCE_ID | $INSTANCE_ID`

If typed, this fails because it is incorrect syntax.
These references should be changed:
`ibmcloud kp create KEY_NAME -i $INSTANCE_ID`

There are 10 occurrences of this on the page cited above.

**Comment by ccbarragan** [comment]
@wmwidener Updated the page to remove the incorrecct syntax.

https://cloud.ibm.com/docs/services/key-protect?topic=key-protect-cli-reference

Thanks for help to improve our docs!
